---
 - hosts: server
   become: true
   tasks:
    - name: Print OS release
      ansible.builtin.file:
        name: /home/server_repo
        state: directory
        owner: root
        group: root
        mode: '0755'
